export enum NeedReportEventType {
  COMMENT = 'COMMENT',
  STATUS_CHANGE = 'STATUS_CHANGE',
  TAG_ADDED = 'TAG_ADDED',
  TAG_REMOVED = 'TAG_REMOVED',
  ASSIGNED = 'ASSIGNED',
  TITLE_EDITED = 'TITLE_EDITED',
}
