export enum NotificationType {
  NEED_ASSIGNED = 'NEED_ASSIGNED',
  NEED_STATUS_CHANGED = 'NEED_STATUS_CHANGED',
  NEED_COMMENT_ADDED = 'NEED_COMMENT_ADDED',
  SERVICE_PUBLISHED = 'SERVICE_PUBLISHED',
  ORG_ACTIVATED = 'ORG_ACTIVATED',
  ORG_REVIEWED = 'ORG_REVIEWED',
  ORG_PENDING_REVIEW = 'ORG_PENDING_REVIEW',
}
